### ISSUE TITLE
该打包工具解决了什么问题

### ISSUE THREAD

**Issue by pansong291** [zimoyin/autox_apk_builder#1]
请教一下，这个打包工具，在原来的基础上做了哪些修改，增加了什么特性，解决了什么问题呢？简单说就是这个项目存在的主要目的和意义。

**Comment by zimoyin** [comment]
好有哲学的问题啊。对比APP打包没啥新特性，就是方便在电脑打包而已

**Comment by zimoyin** [comment]
好有哲学的问题啊。对比APP打包没啥新特性，就是方便在电脑打包而已
